name: elevent
description: 11t is an iOS and Android app for connecting to ActivityPub.

version: 2.0.0+35

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.11.1
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  json_annotation: ^4.0.1
  cached_network_image: ^3.1.0
  flutter_riverpod: ^0.14.0+3
  package_info: ^2.0.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo-11t.jpg
